// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chatroom.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	chatroom.proto

It has these top-level messages:
	Client
	Message
	Event
*/
package pb

import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Client) Validate() error {
	return nil
}
func (this *Message) Validate() error {
	if this.From != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.From); err != nil {
			return go_proto_validators.FieldError("From", err)
		}
	}
	if this.To != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.To); err != nil {
			return go_proto_validators.FieldError("To", err)
		}
	}
	return nil
}
func (this *Event) Validate() error {
	if oneOfNester, ok := this.GetCommand().(*Event_Login); ok {
		if oneOfNester.Login != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Login); err != nil {
				return go_proto_validators.FieldError("Login", err)
			}
		}
	}
	if oneOfNester, ok := this.GetCommand().(*Event_Message); ok {
		if oneOfNester.Message != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Message); err != nil {
				return go_proto_validators.FieldError("Message", err)
			}
		}
	}
	return nil
}
